# Generated by Django 5.2.4 on 2025-07-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0003_alter_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
