# Generated by Django 5.2.4 on 2025-07-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0005_user_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='link',
            new_name='profile_link',
        ),
    ]
